apiVersion: apps/v1
kind: Deployment
metadata:
  name: snap-link-dm
  namespace: snap-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snap-link
  template:
    metadata:
      name: snap-link-pod
      labels:
        app: snap-link
    spec:
      containers:
        - name: snap-link
          image: /snap-link/snap-link:latest
          # If using a local image, use Never, default is Always
          #imagePullPolicy: Never
          command: ["./SnapLink", "-c", "/app/configs/SnapLink.yml"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: snap-link-vl
              mountPath: /app/configs/
              readOnly: true

          ports:
            - name: http-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: http-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: http-port
              path: /health

            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      # todo for private repositories, you need to create a secret (here docker-auth-secret) to store the account and password to log into docker
      imagePullSecrets:
        - name: docker-auth-secret
      volumes:
        - name: snap-link-vl
          configMap:
            name: snap-link-config
