apiVersion: v1
kind: Service
metadata:
  name: snap-link-svc
  namespace: snap-link
spec:
  selector:
    app: snap-link
  type: ClusterIP
  ports:
    - name: snap-link-svc-http-port
      port: 8080
      targetPort: 8080

