// code generated by https://SnapLink

package config

import (
	"github.com/zhufuyi/sponge/pkg/conf"
)

func NewCenter(configFile string) (*Center, error) {
	nacosConf := &Center{}
	err := conf.Parse(configFile, nacosConf)
	return nacosConf, err
}

type Center struct {
	Nacos Nacos `yaml:"nacos" json:"nacos"`
}
